### ISSUE TITLE
Require local composer autoload

### ISSUE THREAD

**Issue by lightningspirit** [AttLii/image-blur#23]
Hi 👋 ,
First of all thanks for this plugin, saves a lot of time on custom code 🥇 .

My WordPress instance has already a root composer autoload. When added this plugin via normal plugin installation it breaks.
A working fix was to use `dirname` which tells PHP to load the plugin's autoload (image-blur.php line 16):
```php
require_once dirname(__FILE__) . '/vendor/autoload.php';
```

**Comment by AttLii** [comment]
Hey,

Nice to know that the plugin is actually in use.

Do you use some public Wordpress template environment to produce this error?
