### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by ChrisEdson** [AttLii/image-blur#27]
Hey there -

I'm trying to install this on a Wordpress site with many images. It's failing to activate - it's just timing out. PHP v7.4, Wordpress 5.9.4.

Do you have any suggested workarounds?

Thank you!

**Comment by AttLii** [comment]
Hey,

I think in a case where media library has a lot of images, you could temporarily try increasing max_execution_time.

**Comment by AttLii** [comment]
I'll close this since I haven't heard back from you. Hopefully what I mentioned above helped with our issue.

**Comment by almightybob** [comment]
I'm having the same Issue, on a site with 5000+ images in the Media Library. I increased the execution_timeout to 720 but to no avail...
