### ISSUE TITLE
Will it work in WP 6.4.2?

### ISSUE THREAD

**Issue by levipadre** [AttLii/image-blur#32]
Hi,

Could you let me know if it's safe to install on v6.4.2?
Also, I would like to know if the data will appear in API, like graphql https://en-gb.wordpress.org/plugins/wp-graphql/?
Thanks

**Comment by AttLii** [comment]
Hey,

I just pushed version 3.0.0.

No problems on 6.4.2 or on the newest version of wp-graphql.

**Comment by levipadre** [comment]
Hi @AttLii. Thank you for the quick response. I can see it is working with WP 6.4.2, however I can't see the blurred data in graphql. Thanks anyway.

**Comment by AttLii** [comment]
Hey, the plugin itself doesn't add the blurred data to the graphql plugin, you can add it with following hook, [link](https://github.com/AttLii/image-blur/blob/main/env/themes/example-theme/plugin-examples/wpgraphql.php).
